background {
    monitor =
    path = ~/Pictures/Wallpapers/wallpaper.jpg
    blur_passes = 3
    blur_size = 7
    brightness = 0.3
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(7c3aed)
    inner_color = rgb(0a0b14)
    font_color = rgb(e2e8f0)
    fade_on_empty = false
    placeholder_text = <span foreground="##94a3b8">🔑 Password...</span>
    hide_input = false
    check_color = rgb(d946ef)
    fail_color = rgb(f43f5e)
    fail_text = <i>$FAIL</i>
    capslock_color = rgb(eab308)
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span foreground='##e2e8f0' font_desc='JetBrainsMono Nerd Font Bold 42'>$(date +"%H:%M")</span>"
    color = rgba(e2e8f0ff)
    font_size = 42
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(d946efcc)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -140
    halign = center
    valign = center
}